# '''
# Copyright (C) 2010-2021 Alibaba Group Holding Limited.
# '''

common:
  #-------basic Hyparameter----------
  visdom:
    enable: False
    visname: UCF101
  dataset: UCF101 #Database name e.g., NTU, THU ...
  init_epochs: 0
  report_freq: 10
  test_batch_size: 40
  dist: True
  vis_feature: True # Visualization?

  scheduler:
    name: cosin
    patience: 4
    warm_up_epochs: 3
  loss:
    name: SoftCE
    labelsmooth: True
  MultiLoss: True
  loss_lamdb: [ 1, 0.5, 0.5, 0.5 ]

model:
  Network: DSNV2 # e.g., DSNV2 or FusionNet
  pretrained: ''
  resumelr: ''
  SYNC_BN: 1
  recoupling: True
  knn_attention: 0.7
  sharpness: True
  temp: [ 0.04, 0.07 ]
  frp: False
  SEHeads: 1
  N: 6 # Number of Transformer Blocks

fusion:
  #-------Used for fusion network----------
  rgb_checkpoint:
    cs16: ''
    cs32: ''
    cs64: ''
  depth_checkpoint:
    cs16: ''
    cs32: ''
    cs64: ''

dataset:
  flip: 0.5
  rotated: 0.5
  angle: (-10, 10) # Rotation angle
  Blur: False
  resize: (320, 240)
  crop_size: 224
  sample_size: 224